import {FormEvent,useEffect,useState} from 'react';
import {Building2,Check,Save} from 'lucide-react';
import {Button,Card,Field,Spinner} from '../components/ui';
import {useAcademy} from '../lib/store';
import {supabase} from '../lib/supabase';
type Profile={name:string;phone:string;email:string;address:string};
export default function SettingsPage(){
 const registerSchool=useAcademy(s=>s.registerSchool),[profile,setProfile]=useState<Profile|null>(null),[done,setDone]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{void supabase.from('schools').select('name,phone,email,address').single().then(({data,error})=>{if(error)setError(error.message);else setProfile({name:data.name,phone:data.phone||'',email:data.email||'',address:data.address||''})})},[]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget),next={name:String(f.get('name')),phone:String(f.get('phone')),email:String(f.get('email')),address:String(f.get('address'))};const {error}=await supabase.from('schools').update(next);setSaving(false);if(error){setError(error.message);return}setProfile(next);registerSchool(next.name);setDone(true);setTimeout(()=>setDone(false),2500)};
 if(!profile&&!error)return <Spinner/>;
 return <div className="mx-auto max-w-3xl"><div className="mb-6"><h2 className="font-display text-2xl font-bold">Paramètres</h2><p className="mt-1 text-sm text-stone-500">Informations enregistrées dans Supabase.</p></div><Card className="overflow-hidden"><div className="flex items-center gap-3 border-b p-5 sm:p-6"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-50 text-brand-700"><Building2 size={21}/></span><div><h3 className="font-display font-bold">Établissement</h3><p className="text-sm text-stone-400">Identité et coordonnées</p></div></div>{profile&&<form onSubmit={submit} className="grid gap-4 p-5 sm:grid-cols-2 sm:p-6"><Field name="name" label="Nom de l’école" defaultValue={profile.name} required/><Field name="phone" label="Téléphone" defaultValue={profile.phone}/><Field name="email" label="E-mail" type="email" defaultValue={profile.email}/><Field name="address" label="Adresse" defaultValue={profile.address}/>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-600 sm:col-span-2">{error}</p>}<div className="flex items-center gap-3 sm:col-span-2"><Button type="submit" disabled={saving}><Save size={16}/>{saving?'Enregistrement…':'Enregistrer'}</Button>{done&&<span className="flex items-center gap-1 text-sm font-semibold text-emerald-600"><Check size={16}/>Modifications enregistrées</span>}</div></form>}</Card></div>
}
